version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ecommerce-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce-db
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network

  ecommerce-service:
    build: .
    command: ["./wait-for-db.sh", "db", "./ecommerce-service"]
    depends_on:
      - db
    environment:
      DB_SOURCE: postgresql://ecommerce-user:password@db:5432/ecommerce-db?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
